baseURL = 'https://variegated.coffee/'
languageCode = 'en-us'
title = 'Variegated Coffee'
theme = 'archie'
copyright = 'Variegated Coffee'

pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
	customcss = ["css/colors.css"]
	mode="light" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "Open source hardware and firmware for espresso machines"
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support
	math = true

[outputs]
  home = ['html', 'rss']
  section = ['html', 'rss']
  taxonomy = ['html']
  term = ['html']

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/variegated-coffee"

[[params.social]]
name = "Discord"
icon = "message-circle"
url = "https://discord.gg/gn9aGHAc3U"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]